### PR TITLE
Allow current elemental versions

### PR DESCRIPTION
**Pull request by tardinha**

### CODE REVIEW

**Comment by nglasl** [comment]
Hey @tardinha thanks for the PR, but just wanted to ask if you managed to give this a whirl? I can't remember if the syntax needed a comma, or only a space. https://getcomposer.org/doc/articles/versions.md suggests that it only needs a space.

**Comment by tardinha** [comment]
yah, but probably not hard enough... i'll ensure my fork is being used and confirm.

**Comment by nglasl** [comment]
@tardinha testing composer requirements with a fork isn't fun, as it usually pulls from upstream. I was thinking a quick test by throwing something like that into your project `composer.json` to make sure it's valid syntax.

**Comment by tardinha** [comment]
I get no errors with or without the comma. But, I have updated it as per the compoer docs.

**Review by nglasl — APPROVED** [review]

**Pull request merged**
